
import java.util.ArrayList;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * accueil.java
 *
 * Created on Dec 14, 2011, 3:50:16 PM
 */
/**
 *
 * @author user
 */
public class acceuil extends javax.swing.JFrame {
 static   int i=3;
public static String passwordd=null,logingg=null;
    /** Creates new form accueil */
    public acceuil() {
        initComponents();
        this.setLocation(300,150);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwor = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(658, 513));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(logi);
        logi.setBounds(210, 160, 220, 30);

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 210, 110, 30);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 320, 110, 40);

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 160, 110, 30);

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 24));
        jLabel5.setText("Zakaria Ouhrochan &  Fatimzahra GHazali");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 420, 430, 40);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 350, 30, 30);
        getContentPane().add(passwor);
        passwor.setBounds(210, 210, 220, 30);

        jLabel7.setText("mot de passe oublié");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jLabel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel7KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 280, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bypiratxx1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
REQUETE_SQL.connexionbase();
}//GEN-LAST:event_formWindowOpened

private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    String log="";
        log=logi.getText();
       logingg=log; 
String pass="";
        pass=passwor.getText();
   passwordd=pass;
        pageprincipale pp=new pageprincipale();     
 pageprincipale_resept ppr=new pageprincipale_resept();
   if (REQUETE_SQL.authentification(log, pass) && !log.equals("")&& !pass.equals("")){
       if(log.equals("receptionniste")){
         
          ppr.setVisible(true);
       }else{
pp.setVisible(true);}
this.setVisible(false);
}
   else{
   javax.swing.JOptionPane.showMessageDialog(null,"Login ou Password incorrect \n il vous reste :"+(i-1)+" tentative"); 
i--;
   if (i==0){
       javax.swing.JOptionPane.showMessageDialog(null,"NOMBRE DE TENTATIVES EPUISE \n Veuillez contacter l'administrateur"); 
   this.setVisible(false);
   }
   }



    
    
}//GEN-LAST:event_jLabel2MouseClicked

private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
}//GEN-LAST:event_jLabel2MouseEntered

private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
jLabel2.setBorder(null);
}//GEN-LAST:event_jLabel2MouseExited

private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
this.setVisible(false);
}//GEN-LAST:event_jLabel6MouseClicked

private void jLabel7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel7KeyPressed

}//GEN-LAST:event_jLabel7KeyPressed

private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
mot_de_passe_oublierJF mps=new mot_de_passe_oublierJF();
mps.question.removeAllItems();
ArrayList<String> h=REQUETE_SQL.tous_question_secret();
for(int ifi=0;ifi<h.size();ifi++)
mps.question.addItem(h.get(ifi));
mps.setVisible(true);

}//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new acceuil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField logi;
    private javax.swing.JPasswordField passwor;
    // End of variables declaration//GEN-END:variables
}
