


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientJFrame.java
 *
 * Created on Dec 15, 2011, 11:22:10 PM
 */
/**
 *
 * @author user
 */
public class ClientJFrame extends javax.swing.JFrame {
static String  cin_g=null;
    /** Creates new form ClientJFrame */
    public ClientJFrame() {
        initComponents();
        this.setLocation(300, 0);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ID_Client = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Adresse = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        Prenom = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 670));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        ID_Client.setFont(new java.awt.Font("Footlight MT Light", 0, 14));
        ID_Client.setEnabled(false);
        getContentPane().add(ID_Client);
        ID_Client.setBounds(310, 120, 166, 30);

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 14));
        jLabel2.setText("ID_Client  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 120, 129, 27);

        cin.setFont(new java.awt.Font("Footlight MT Light", 0, 14));
        cin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cinKeyReleased(evt);
            }
        });
        getContentPane().add(cin);
        cin.setBounds(310, 80, 166, 30);

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 14));
        jLabel1.setText("CIN  :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 80, 129, 27);

        Adresse.setColumns(20);
        Adresse.setRows(5);
        Adresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AdresseKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Adresse);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(310, 170, 166, 96);

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 1, 14));
        jLabel4.setText("Adresse   :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 200, 129, 27);

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 14));
        jLabel3.setText("Nom  :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 280, 129, 27);

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 1, 14));
        jLabel6.setText("Prenom  :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 320, 129, 27);

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 1, 14));
        jLabel5.setText("Telephone :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 360, 129, 27);

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 1, 14));
        jLabel7.setText("Email  :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 410, 129, 27);

        Nom.setFont(new java.awt.Font("Footlight MT Light", 0, 14));
        Nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NomKeyReleased(evt);
            }
        });
        getContentPane().add(Nom);
        Nom.setBounds(310, 280, 170, 30);

        Prenom.setFont(new java.awt.Font("Footlight MT Light", 0, 14));
        Prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PrenomKeyReleased(evt);
            }
        });
        getContentPane().add(Prenom);
        Prenom.setBounds(310, 320, 170, 30);

        telephone.setFont(new java.awt.Font("Footlight MT Light", 0, 14));
        telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telephoneKeyReleased(evt);
            }
        });
        getContentPane().add(telephone);
        telephone.setBounds(310, 360, 170, 30);

        Email.setFont(new java.awt.Font("Footlight MT Light", 0, 14));
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailKeyReleased(evt);
            }
        });
        getContentPane().add(Email);
        Email.setBounds(310, 410, 170, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(80, 400, 520, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(110, 160, 480, 20);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(110, 160, 480, 20);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(110, 160, 480, 20);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(110, 160, 480, 20);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(110, 160, 480, 20);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(90, 270, 510, 20);

        Annuler.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(Annuler);
        Annuler.setBounds(340, 470, 110, 30);

        Valider.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(Valider);
        Valider.setBounds(210, 470, 110, 30);

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 80, 120, 30);

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(490, 410, 110, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zak.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 660, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed

    reservation_jframe rsjf=new reservation_jframe();
   
    boolean fl=REQUETE_SQL.ajouter_client(cin.getText(), Nom.getText(),Prenom.getText(), Adresse.getText(), telephone.getText(),Email.getText());
  cin_g=cin.getText();
if(fl==true){
       String ii= REQUETE_SQL.Id_Dernier_Client();
       Integer i;
    try {
         i = Integer.parseInt(ii)+1;
    } catch (Exception e) {i=1;
    }
      
ID_Client.setText(i+""); 
 cin.setText(""); Nom.setText("");Prenom.setText(""); Adresse.setText(""); telephone.setText("");Email.setText("");
   this.setVisible(false);
    rsjf.setVisible(true);
   }else{
 
    javax.swing.JOptionPane.showMessageDialog(null,"le  CIN éxiste déja"); 
     
   
   } 
    
    
}//GEN-LAST:event_ValiderActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

REQUETE_SQL.connexionbase();
String ii= REQUETE_SQL.Id_Dernier_Client();
Integer i;
    try {        
   
        i= Integer.parseInt(ii)+1;
         } catch (Exception e) {i=1;
    }
ID_Client.setText(i+"");
}//GEN-LAST:event_formWindowOpened

private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
this.setVisible(false);
}//GEN-LAST:event_AnnulerActionPerformed

private void cinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cinKeyReleased
String v=cin.getText();
if(v.length()>8){cin.setText(v.substring(0,8));
}
if (v.contains(";")||v.contains(".")||v.contains(",")||v.contains("'")||v.contains("(")||v.contains(":")||v.contains("-")||v.contains("'")||v.contains("_")||v.contains("+")||v.contains(" "))
   cin.setText(v.substring(0,v.length()-1));
else
    jLabel9.setText("");
}//GEN-LAST:event_cinKeyReleased

private void NomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomKeyReleased
String  v= Nom.getText();
    if (v.contains(";")||v.contains(".")||v.contains(",")||v.contains("'")||v.contains("(")||v.contains(":")||v.contains("-")||v.contains("'")||v.contains("_")||v.contains("+")||v.contains(" "))
   Nom.setText(v.substring(0,v.length()-1));

   
}//GEN-LAST:event_NomKeyReleased

private void AdresseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdresseKeyReleased
String  v= Adresse.getText();
    if (v.contains(";")||v.contains(".")||v.contains(",")||v.contains("'")||v.contains("(")||v.contains(":")||v.contains("-")||v.contains("'")||v.contains("_")||v.contains("+"))
    Adresse.setText(v.substring(0,v.length()-1));

}//GEN-LAST:event_AdresseKeyReleased

private void PrenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrenomKeyReleased
String  v= Prenom.getText();
    if (v.contains(";")||v.contains(".")||v.contains(",")||v.contains("'")||v.contains("(")||v.contains(":")||v.contains("-")||v.contains("'")||v.contains("_")||v.contains("+"))
    Prenom.setText(v.substring(0,v.length()-1));
    
    // TODO add your handling code here:
}//GEN-LAST:event_PrenomKeyReleased

private void telephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneKeyReleased
String  v= telephone.getText();
    try {
        Integer a= Integer.valueOf(v);
    } catch (Exception e) { 
        telephone.setText(v.substring(0,v.length()-1));
    }
   
}//GEN-LAST:event_telephoneKeyReleased

private void EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyReleased
 String  v= Email.getText();
    if (v.contains(";")||v.contains("\\")||v.contains(",")||v.contains("'")||v.contains("(")||v.contains(":")||v.contains("-")||v.contains("'")||v.contains(" ")||v.contains("+")||v.contains(" "))
    Email.setText(v.substring(0,v.length()-1));
    if(v.indexOf('@')==0|| v.indexOf('@')!=v.lastIndexOf('@')||v.lastIndexOf('.')<v.lastIndexOf('@')|| v.lastIndexOf('.')+4<v.length()){
    jLabel10.setText("Email invalide");
}else
         jLabel10.setText("");
    
}//GEN-LAST:event_EmailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ClientJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Adresse;
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField ID_Client;
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField Prenom;
    private javax.swing.JButton Valider;
    private javax.swing.JTextField cin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables
}
