/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * supp_client.java
 *
 * Created on 18 déc. 2011, 19:31:30
 */
/**
 *
 * @author GHAZALI
 */
public class supp_client extends javax.swing.JFrame {

    /** Creates new form supp_client */
    public supp_client() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Annuler = new javax.swing.JButton();
        Valider2 = new javax.swing.JButton();
        cin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(535, 370));
        getContentPane().setLayout(null);

        Annuler.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(Annuler);
        Annuler.setBounds(250, 250, 110, 40);

        Valider2.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        Valider2.setText("Valider");
        Valider2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valider2ActionPerformed(evt);
            }
        });
        getContentPane().add(Valider2);
        Valider2.setBounds(90, 250, 110, 40);

        cin.setFont(new java.awt.Font("Footlight MT Light", 0, 14));
        cin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cinKeyReleased(evt);
            }
        });
        getContentPane().add(cin);
        cin.setBounds(170, 160, 166, 30);

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Entrez le cin de client ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 250, 27);

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CIN  :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 160, 68, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda-cloud-interface[1].jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 520, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
this.setVisible(false);
}//GEN-LAST:event_AnnulerActionPerformed

private void Valider2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valider2ActionPerformed
REQUETE_SQL.connexionbase();
    Object[] options = {"Oui","Non","Annuler!"};
if(REQUETE_SQL.test_cin_Client(cin.getText())==true){javax.swing.JOptionPane.showMessageDialog(null,"le  CIN n'éxiste pas"); }
else{
int n = javax.swing.JOptionPane.showOptionDialog(this,"Voulez -vous vraiment supprimer le client ?","Que voulez vous faire ?", javax.swing.JOptionPane.YES_NO_CANCEL_OPTION,javax.swing.JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
if (n==0) 
{
    REQUETE_SQL.supprimer_client_manjdar(cin.getText());
javax.swing.JOptionPane.showMessageDialog(null,"Les Client a été supprimer"); 
this.setVisible(false);
}
if (n==1) 
{this.setVisible(false);
}
}  
}//GEN-LAST:event_Valider2ActionPerformed

private void cinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cinKeyReleased
String v=cin.getText();
if(v.length()>8){cin.setText(v.substring(0,8));
}
if (v.contains(";")||v.contains(".")||v.contains(",")||v.contains("'")||v.contains("(")||v.contains(":")||v.contains("-")||v.contains("'")||v.contains("_")||v.contains("+")||v.contains(" "))
   cin.setText(v.substring(0,v.length()-1));// TODO add your handling code here:
}//GEN-LAST:event_cinKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supp_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supp_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supp_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supp_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new supp_client().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton Valider2;
    private javax.swing.JTextField cin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
