
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tous_client.java
 *
 * Created on 18 déc. 2011, 17:47:26
 */
/**
 *
 * @author GHAZALI
 */
public class tous_client extends javax.swing.JFrame {

    /** Creates new form tous_client */
    public tous_client() {
        initComponents();
        this.setLocation(320, 100);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settings2.png"))); // NOI18N
        jLabel9.setText("Supprimer");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settings2.png"))); // NOI18N
        jLabel11.setText("Modifier un Client");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_client", "CIN", "Nom", "Prenom", "adresse", "Email", "Telephone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel12.setText("Tous les clients :");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel12)
                .addContainerGap(403, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel12)
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
}//GEN-LAST:event_jLabel9MouseEntered

private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
jLabel9.setBorder(null);
}//GEN-LAST:event_jLabel9MouseExited

private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
// TODO add your handling code here:
}//GEN-LAST:event_jLabel11MouseEntered

private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
jLabel11.setBorder(null);// TODO add your handling code here:
}//GEN-LAST:event_jLabel11MouseExited

private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
// TODO add your handling code here:
}//GEN-LAST:event_jLabel12MouseEntered

private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
// TODO add your handling code here:
}//GEN-LAST:event_jLabel12MouseExited

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
REQUETE_SQL.connexionbase();
    ArrayList<table_info>h=REQUETE_SQL.info_client();
table_info a;
DefaultTableModel md=new DefaultTableModel();
md.setColumnIdentifiers(new String[]{"Id_client","CIN","Nom","Prenom","adresse","Email","Telephone"});
for(int i=0;i<h.size();i++){
    a=h.get(i);
md.addRow(new Object[]{a.id_client,a.cin,a.nom,a.prenom,a.adresse,a.email,a.tele});
}
jTable1.setModel(md);

}//GEN-LAST:event_formWindowOpened

private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
 ModifierclientJF md=new ModifierclientJF();
 String s=null;
    try {
         s= jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
          table_info v=REQUETE_SQL.info_client(s);

    md.cin.setText(v.cin);   
    md.Adresse.setText(v.adresse);
    md.Email.setText(v.email);
    md.Nom.setText(v.nom);
    md.Prenom.setText(v.prenom);
    md.Email.setText(v.email);
    md.ID_Client.setText(v.id_client);
    md.telephone.setText(v.tele);
    
    md.setVisible(true);
     
     
    
    } catch (Exception e) {
       javax.swing.JOptionPane.showMessageDialog(null,"Vous n'avez rien selectionner");    
    }
 
 //_____________________actualiser__________________________
    
    
     ArrayList<table_info>h=REQUETE_SQL.info_client();
table_info a;
DefaultTableModel mdd=new DefaultTableModel();
mdd.setColumnIdentifiers(new String[]{"Id_client","CIN","Nom","Prenom","adresse","Email","Telephone"});
for(int i=0;i<h.size();i++){
    a=h.get(i);
mdd.addRow(new Object[]{a.id_client,a.cin,a.nom,a.prenom,a.adresse,a.email,a.tele});
}
jTable1.setModel(mdd);
   

}//GEN-LAST:event_jLabel11MouseClicked

private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
String s=null;
    try {
         s= jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
    Object[] options = {"Oui","Non","Annuler!"};


int n = javax.swing.JOptionPane.showOptionDialog(this,"Voulez -vous vraiment supprimer le client ?","Que voulez vous faire ?", javax.swing.JOptionPane.YES_NO_CANCEL_OPTION,javax.swing.JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
if (n==0) 
{
    REQUETE_SQL.supprimer_client_manjdar(s);
javax.swing.JOptionPane.showMessageDialog(null,"Les Client a été supprimer"); 

}

  } catch (Exception e) {
       javax.swing.JOptionPane.showMessageDialog(null,"Vous n'avez rien selectionner");    
    }
    
    //_____________________actualiser__________________________
    
    
     ArrayList<table_info>h=REQUETE_SQL.info_client();
table_info a;
DefaultTableModel md=new DefaultTableModel();
md.setColumnIdentifiers(new String[]{"Id_client","CIN","Nom","Prenom","adresse","Email","Telephone"});
for(int i=0;i<h.size();i++){
    a=h.get(i);
md.addRow(new Object[]{a.id_client,a.cin,a.nom,a.prenom,a.adresse,a.email,a.tele});
}
jTable1.setModel(md);

    

}//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tous_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tous_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tous_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tous_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new tous_client().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
